### ISSUE TITLE
git tag for 1.1.0

### ISSUE THREAD

**Issue by pgajdos** [pnpnpn/retry-decorator#14]
Could you please tag 1.1.0?

**Comment by jheld** [comment]
FYI #17 this likely will be what you're looking for. We have released 1.1.1 (no internal changes, just py2-py3 universal wheel).

going forward we intend to only be py3 compatible. any requests for py27 backports of features on newer releases will be case by case.

bugfixes will still be considered for issues that can be resolved, against this branch, as needed, but again, we intend all changes to be after we make py3 only (which is intended to be the next release).

Please re-open if you have additional questions/concerns.
