### ISSUE TITLE
Please add per-file licenses

### ISSUE THREAD

**Issue by petrcermak** [pnpnpn/retry-decorator#4]
The Chromium project (www.chromium.org) pulls in retry-decorator indirectly through the catapult (https://github.com/catapult-project/catapult/) and gsutil (https://github.com/GoogleCloudPlatform/gsutil) source repositories. In order for Chromium to be pulled into various Linux source distributions there's a requirement that all of the third party files pass the Linux <tt>licensecheck</tt> utility. Currently there are many files in the retry-decorator repository missing per-file licenses. From a current run of <tt>licensecheck</tt>, they are:

```
$ licensecheck -r . | grep "No copyright"
./setup.py: *No copyright* UNKNOWN
./retry_decorator/__init__.py: *No copyright* UNKNOWN
./retry_decorator/retry_decorator.py: *No copyright* UNKNOWN
```

We'd like to ask that per-file licenses be added to these files to make it easier to integrate retry-decorator not only into Chromium, but also Linux distributions in general. Thanks.

**Comment by pnpnpn** [comment]
What's the format I have to use? Feel free to make a pull request.
