### ISSUE TITLE
universal wheel

### ISSUE THREAD

**Issue by jheld** [pnpnpn/retry-decorator#8]
Hi!

Could you add a `setup.cfg` and enable the bdist universal option?

```
[bdist_wheel]
universal = 1
```

It would make installing the library via py2 and py3 easier.

And then upload this wheel to PyPI as a new version?

**Comment by jheld** [comment]
@pnpnpn we've been using a custom wheel like this for 2 years now -- it's worked great.

Are you open to having additional PRs to this project to make it only py3 based?

Or maybe just code changes in general?

Are you open to having additional maintainers?

**Comment by pnpnpn** [comment]
> @pnpnpn we've been using a custom wheel like this for 2 years now -- it's worked great.
> 
> Are you open to having additional PRs to this project to make it only py3 based?

Yes, with a version bump. 


> 
> Are you open to having additional maintainers?

Sure. 😄

**Comment by jheld** [comment]
Awesome. Yes, definitely a version bump.

I have contributed a bit in the past -- I'd be happy to have more involvement/permissions.

I would recommend first that we release the current code (adding the universal wheel) just so that people that are looking to port to py3 but haven't yet can at least use the library for both during their upgrade process.

But, any new code would be after py3 only's version bump.

**Comment by jheld** [comment]
#17 implements this! closing.
